apiVersion: v1
kind: LimitRange
metadata:
  namespace: example-ns
  name: example
spec:
  limits:
    - type: Pod # 指定Pod的资源limits
      min: # pod中所有容器的最大最小值
        cpu: 50m
        memory: 5Mi
      max:
        cpu: 1
        memory: 1Gi
    - type: Container
      defaultRequest:  # 容器没有指定CPU或内存请求量时设置的默认值
        cpu: 100m
        memory: 100Mi
      default: # 没指定limits时设定的默认值
        cpu: 200m
        momery: 100Mi
      min:
        cpu: 50m
        memory: 5Gi
      max:
        cpu: 1
        momery: 1Gi
      maxLimitRequestRatio: # 每种资源requests与limits的最大比值
        cpu: 4
        memory: 1Gi
    - type: PersisitentVolumeClain # PVC存储容量
      min:
        storage: 1Gi
      max:
        storage: 10Gi