apiVersion: v1
kind: Pod
metadata:
  name: app-pod
spec:
  # nodeName:
  containers:
    - name: main
      image: busybox
      command: ["dd", "if=/dev/zero", "of=/dev/null"]
      resources:
        requests:
          cpu: 200m
          memory: 10Mi
        limits:
          cpu: 1
          memory: 200Mi
