name: Go
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build: # job id
    name: Test
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/hello-world-javascript-action
      - name: Set up Go 1.13
        uses: actions/steup-go@v1
        with:
          go-version: 1.13
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Test
        run: script/test.sh